-- retrieve a list of unique countries from which customers originate
SELECT DISTINCT
country
from gold.dim_customers
order by country;
-- retrieve a list of unique categories,subcat and prod 
SELECT DISTINCT
category,
subcategory,
product_name
from gold.dim_products
order by category,subcategory,product_name
-- determine the first and last order date and total duration in months
select
MIN(order_date) as first_order_date,
MAX(order_date) as first_order_date,
DATEDIFF(MONTH,min(order_date) , max(order_date)) as order_range_month
FROM GOLD.fact_sales
-- find the youngest and oldest customer based on the birthdate
SELECT
MIN(birthdate) as oldest_birthdate,
DATEDIFF(year,MIN(birthdate),getdate()) as oldest_age, 
MAX(birthdate) as youngest_birthdate,
DATEDIFF(year,MAX(birthdate),getdate()) as youngest_age
from gold.dim_customers;

-- Measure Exploration
-- find the total sales
SELECT sum(sales_amount) as total_sales from gold.fact_sales
-- find thow many items were sold
SELECT sum(quantity) as total_quantity from gold.fact_sales
-- find the avg selling price
SELECT avg(price) as avg_price from gold.fact_sales
-- find the total number of oders
SELECT count(order_number) as total_orders from gold.fact_sales
SELECT count(DISTINCT order_number) as total_orders from gold.fact_sales
-- find the total number of products
SELECT count(product_name) as total_products from gold.dim_products
SELECT count( DISTINCT product_name) as total_products from gold.dim_products
-- find the total number of products
SELECT count(customer_key) as total_customers from gold.dim_customers
-- find the total number of customers that placed an order
SELECT count(DISTINCT customer_key) as total_customers from gold.fact_sales


-- Generate a report that shows all key metrics of the business

SELECT 'Total Sales' as measure_name , sum(sales_amount) as measure_value from gold.fact_sales
UNION ALL
SELECT 'Total Quantity', sum(quantity)  from gold.fact_sales
UNION ALL
SELECT 'Average price', avg(price)  from gold.fact_sales
UNION ALL
SELECT 'Total Orders', Count(DISTINCT order_number)  from gold.fact_sales
UNION ALL
SELECT 'Total products',Count(DISTINCT product_name) from gold.dim_products 
union all
SELECT 'total Customers',Count(customer_key) from gold.dim_customers

--Magnitude Analysis
-- find th total customers by countries
select
COUNTRY,
count(customer_key) as total_cutomers
from gold.dim_customers
group by COUNTRY order by total_cutomers DESC
-- find the total customers by gender
select
gender,
count(customer_key) as total_cutomers
from gold.dim_customers
group by gender order by total_cutomers DESC
-- find the total products by category
select
category,
count(product_key) as total_products
from gold.dim_products
group by category
order by total_products DESC
-- what is the average cost in each cat
select
category,
avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg_cost DESC
--What is the total rev generated by each category
SELECT
p.category,
sum(f.sales_amount) as total_rev
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by p.category ORDER BY total_rev DESC

-- What is the distribution of sold items across countries ?
SELECT
c.COUNTRY,
sum(f.quantity) as total_sold_items
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by c.country
order by total_sold_items  DESC

-- Which 5 products generate the highest rev ?
SELECT TOP 5
p.product_name,
sum(f.sales_amount) as total_rev
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by
p.product_name
ORDER BY total_rev DESC
-- Which 5 products generate the LOWEST rev ?
SELECT TOP 5
p.product_name,
sum(f.sales_amount) as total_rev
from gold.fact_sales f
left join gold.dim_products p
on p.product_key = f.product_key
group by
p.product_name
ORDER BY total_rev ASC

--Find the top 10 Customers who have generated the highest rev
SELECt TOP 5
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on c.customer_key = f.customer_key
group by 
c.customer_key,
c.first_name,
c.last_name
order by total_revenue DESC;
